package fastlystats

import "google.golang.org/genproto/googleapis/api/metric"

var MetricDescriptors = []*metric.MetricDescriptor{
	{
		Name:        "requests",
		Type:        "custom.googleapis.com/fastly/requests",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests processed.",
		DisplayName: "Request Count",
	},
	{
		Name:        "hits",
		Type:        "custom.googleapis.com/fastly/hits",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of cache hits.",
		DisplayName: "Cache Hits",
	},
	{
		Name:        "hits_time",
		Type:        "custom.googleapis.com/fastly/hits_time",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_DOUBLE,
		Unit:        "s",
		Description: "Total amount of time spent processing cache hits (in seconds).",
		DisplayName: "Hits Time",
	},
	{
		Name:        "miss",
		Type:        "custom.googleapis.com/fastly/miss",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of cache misses.",
		DisplayName: "Cache Miss",
	},
	{
		Name:        "miss_time",
		Type:        "custom.googleapis.com/fastly/miss_time",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_DOUBLE,
		Unit:        "s",
		Description: "Amount of time spent processing cache misses (in seconds).",
		DisplayName: "Miss Time",
	},
	{
		Name:        "pass",
		Type:        "custom.googleapis.com/fastly/pass",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests that passed through the CDN without being cached.",
		DisplayName: "Cache Pass",
	},
	{
		Name:        "pass_time",
		Type:        "custom.googleapis.com/fastly/pass_time",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_DOUBLE,
		Unit:        "s",
		Description: "Amount of time spent processing cache misses (in seconds).",
		DisplayName: "Pass Time",
	},
	{
		Name:        "synth",
		Type:        "custom.googleapis.com/fastly/synth",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests that returned synth response.",
		DisplayName: "Synth",
	},
	{
		Name:        "errors",
		Type:        "custom.googleapis.com/fastly/errors",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of cache errors.",
		DisplayName: "Errors",
	},
	{
		Name:        "restarts",
		Type:        "custom.googleapis.com/fastly/restarts",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of restarts performed.",
		DisplayName: "Restarts",
	},
	{
		Name:        "hit_ratio",
		Type:        "custom.googleapis.com/fastly/hit_ratio",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_DOUBLE,
		Unit:        "10^2.%",
		Description: "Global Cache Hit ratio, defined as hits/requests",
		DisplayName: "Cache Hit Ratio",
	},
	{
		Name:        "bandwidth",
		Type:        "custom.googleapis.com/fastly/bandwidth",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total bytes delivered (body_size + header_size).",
		DisplayName: "Bandwidth",
	},
	{
		Name:        "req_body_bytes",
		Type:        "custom.googleapis.com/fastly/req_body_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total body bytes received.",
		DisplayName: "Request Body Bytes",
	},
	{
		Name:        "req_header_bytes",
		Type:        "custom.googleapis.com/fastly/req_header_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total header bytes received.",
		DisplayName: "Request Header Bytes",
	},
	{
		Name:        "resp_body_bytes",
		Type:        "custom.googleapis.com/fastly/resp_body_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total body bytes delivered.",
		DisplayName: "Response Body Bytes",
	},
	{
		Name:        "resp_header_bytes",
		Type:        "custom.googleapis.com/fastly/resp_header_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total header bytes delivered.",
		DisplayName: "Response Header Bytes",
	},
	{
		Name:        "bereq_body_bytes",
		Type:        "custom.googleapis.com/fastly/bereq_body_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total body bytes sent to origin.",
		DisplayName: "Backend Request Body Bytes",
	},
	{
		Name:        "bereq_header_bytes",
		Type:        "custom.googleapis.com/fastly/bereq_header_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total header bytes sent to origin.",
		DisplayName: "Backend Request Header Bytes",
	},
	{
		Name:        "uncachable",
		Type:        "custom.googleapis.com/fastly/uncachable",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Number of requests that were designated uncachable.",
		DisplayName: "Uncachable",
	},
	{
		Name:        "pipe",
		Type:        "custom.googleapis.com/fastly/pipe",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Optional. Pipe operations performed (legacy feature).",
		DisplayName: "Pipe",
	},
	{
		Name:        "tls",
		Type:        "custom.googleapis.com/fastly/tls",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests that were received over TLS.",
		DisplayName: "TLS",
	},
	{
		Name:        "tls_v10",
		Type:        "custom.googleapis.com/fastly/tls_v10",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests received over TLS 1.0.",
		DisplayName: "TLS v1.0",
	},
	{
		Name:        "tls_v11",
		Type:        "custom.googleapis.com/fastly/tls_v11",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests received over TLS 1.1.",
		DisplayName: "TLS v1.1",
	},
	{
		Name:        "tls_v12",
		Type:        "custom.googleapis.com/fastly/tls_v12",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests received over TLS 1.2.",
		DisplayName: "TLS v1.2",
	},
	{
		Name:        "tls_v13",
		Type:        "custom.googleapis.com/fastly/tls_v13",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests received over TLS 1.3.",
		DisplayName: "TLS v1.3",
	},
	{
		Name:        "shield",
		Type:        "custom.googleapis.com/fastly/shield",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests from shield to origin.",
		DisplayName: "Shield",
	},
	{
		Name:        "shield_resp_body_bytes",
		Type:        "custom.googleapis.com/fastly/shield_resp_body_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total body bytes delivered via a shield.",
		DisplayName: "Shield Response Body Bytes",
	},
	{
		Name:        "shield_resp_header_bytes",
		Type:        "custom.googleapis.com/fastly/shield_resp_header_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total header bytes delivered via a shield.",
		DisplayName: "Shield Response Header Bytes",
	},
	{
		Name:        "ipv6",
		Type:        "custom.googleapis.com/fastly/ipv6",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests that were received over IPv6.",
		DisplayName: "IPv6",
	},
	{
		Name:        "otfp",
		Type:        "custom.googleapis.com/fastly/otfp",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses that came from the Fastly On-the-Fly Packager for On Demand Streaming service for video-on-demand.",
		DisplayName: "On-The-Fly Packing",
	},
	{
		Name:        "video",
		Type:        "custom.googleapis.com/fastly/video",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses that came from the Fastly On-the-Fly Packager for On Demand Streaming service for video-on-demand.",
		DisplayName: "On-The-Fly Packing",
	},
	{
		Name:        "pci",
		Type:        "custom.googleapis.com/fastly/pci",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses with the PCI flag turned on.",
		DisplayName: "PCI",
	},
	{
		Name:        "log",
		Type:        "custom.googleapis.com/fastly/log",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of log lines sent.",
		DisplayName: "log",
	},
	{
		Name:        "http2",
		Type:        "custom.googleapis.com/fastly/http2",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests received over HTTP2.",
		DisplayName: "HTTP/2",
	},
	{
		Name:        "waf_logged",
		Type:        "custom.googleapis.com/fastly/waf_logged",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests that triggered a WAF rule and were logged.",
		DisplayName: "Web Application Firewall Logged",
	},
	{
		Name:        "waf_blocked",
		Type:        "custom.googleapis.com/fastly/waf_blocked",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests that triggered a WAF rule and were blocked.",
		DisplayName: "Web Application Firewall Blocked",
	},
	{
		Name:        "waf_passed",
		Type:        "custom.googleapis.com/fastly/waf_passed",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of requests that triggered a WAF rule and were passed.",
		DisplayName: "Web Application Firewall Passed",
	},
	{
		Name:        "attack_req_body_bytes",
		Type:        "custom.googleapis.com/fastly/attack_req_body_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Number of requests that triggered a WAF rule and were passed.",
		DisplayName: "Attack Request Body Bytes",
	},
	{
		Name:        "attack_req_header_bytes",
		Type:        "custom.googleapis.com/fastly/attack_req_header_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Number of requests that triggered a WAF rule and were passed.",
		DisplayName: "Attack Request Header Bytes",
	},
	{
		Name:        "attack_resp_synth_bytes",
		Type:        "custom.googleapis.com/fastly/attack_resp_synth_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Total bytes delivered for requests that triggered a WAF rule and returned a synthetic response.",
		DisplayName: "Attack Response Synthetic Bytes",
	},
	{
		Name:        "imgopto",
		Type:        "custom.googleapis.com/fastly/imgopto",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses that came from the Fastly Image Optimizer service.",
		DisplayName: "Image Optimizer",
	},
	{
		Name:        "status_200",
		Type:        "custom.googleapis.com/fastly/status_200",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 200 (Success).",
		DisplayName: "HTTP Status 200",
	},
	{
		Name:        "status_204",
		Type:        "custom.googleapis.com/fastly/status_204",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 204 (No Content).",
		DisplayName: "HTTP Status 204",
	},
	{
		Name:        "status_206",
		Type:        "custom.googleapis.com/fastly/status_206",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 206 (Partial Content).",
		DisplayName: "HTTP Status 206",
	},
	{
		Name:        "status_301",
		Type:        "custom.googleapis.com/fastly/status_301",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 301 (Moved Permanently).",
		DisplayName: "HTTP Status 301",
	},
	{
		Name:        "status_302",
		Type:        "custom.googleapis.com/fastly/status_302",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 302 (Found).",
		DisplayName: "HTTP Status 302",
	},
	{
		Name:        "status_304",
		Type:        "custom.googleapis.com/fastly/status_304",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 304 (Not Modified).",
		DisplayName: "HTTP Status 304",
	},
	{
		Name:        "status_400",
		Type:        "custom.googleapis.com/fastly/status_400",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 400 (Bad Request).",
		DisplayName: "HTTP Status 400",
	},
	{
		Name:        "status_401",
		Type:        "custom.googleapis.com/fastly/status_401",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 401 (Unauthorized).",
		DisplayName: "HTTP Status 401",
	},
	{
		Name:        "status_403",
		Type:        "custom.googleapis.com/fastly/status_403",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 403 (Forbidden).",
		DisplayName: "HTTP Status 403",
	},
	{
		Name:        "status_404",
		Type:        "custom.googleapis.com/fastly/status_404",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 404 (Not Found).",
		DisplayName: "HTTP Status 404",
	},
	{
		Name:        "status_416",
		Type:        "custom.googleapis.com/fastly/status_416",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 416 (Range Not Satisfiable).",
		DisplayName: "HTTP Status 416",
	},
	{
		Name:        "status_500",
		Type:        "custom.googleapis.com/fastly/status_500",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 500 (Internal Server Error).",
		DisplayName: "HTTP Status 500",
	},
	{
		Name:        "status_501",
		Type:        "custom.googleapis.com/fastly/status_501",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 501 (Not Implemented).",
		DisplayName: "HTTP Status 501",
	},
	{
		Name:        "status_502",
		Type:        "custom.googleapis.com/fastly/status_502",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 502 (Bad Gateway).",
		DisplayName: "HTTP Status 502",
	},
	{
		Name:        "status_503",
		Type:        "custom.googleapis.com/fastly/status_503",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 503 (Service Unavailable).",
		DisplayName: "HTTP Status 503",
	},
	{
		Name:        "status_504",
		Type:        "custom.googleapis.com/fastly/status_504",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 504 (Gateway Timeout).",
		DisplayName: "HTTP Status 504",
	},
	{
		Name:        "status_505",
		Type:        "custom.googleapis.com/fastly/status_505",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of responses sent with status code 505 (HTTP Version Not Supported).",
		DisplayName: "HTTP Status 505",
	},
	{
		Name:        "status_1xx",
		Type:        "custom.googleapis.com/fastly/status_1xx",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of \"Informational\" status codes delivered.",
		DisplayName: "HTTP Status 1xx",
	},
	{
		Name:        "status_2xx",
		Type:        "custom.googleapis.com/fastly/status_2xx",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of \"Success\" status codes delivered.",
		DisplayName: "HTTP Status 2xx",
	},
	{
		Name:        "status_3xx",
		Type:        "custom.googleapis.com/fastly/status_3xx",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of \"Redirection\" status codes delivered.",
		DisplayName: "HTTP Status 3xx",
	},
	{
		Name:        "status_4xx",
		Type:        "custom.googleapis.com/fastly/status_4xx",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of \"Client Error\" status codes delivered.",
		DisplayName: "HTTP Status 4xx",
	},
	{
		Name:        "status_5xx",
		Type:        "custom.googleapis.com/fastly/status_5xx",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of \"Server Error\" status codes delivered.",
		DisplayName: "HTTP Status 5xx",
	},
	{
		Name:        "object_size_1k",
		Type:        "custom.googleapis.com/fastly/object_size_1k",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of objects served that were under 1KB in size.",
		DisplayName: "Object Size 1KB",
	},
	{
		Name:        "object_size_10k",
		Type:        "custom.googleapis.com/fastly/object_size_10k",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of objects served that were between 1KB and 10KB in size.",
		DisplayName: "Object Size 10KB",
	},
	{
		Name:        "object_size_100k",
		Type:        "custom.googleapis.com/fastly/object_size_100k",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of objects served that were between 10KB and 100KB in size.",
		DisplayName: "Object Size 100KB",
	},
	{
		Name:        "object_size_1m",
		Type:        "custom.googleapis.com/fastly/object_size_1m",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of objects served that were between 100KB and 1MB in size.",
		DisplayName: "Object Size 1MB",
	},
	{
		Name:        "object_size_10m",
		Type:        "custom.googleapis.com/fastly/object_size_10m",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of objects served that were between 1MB and 10MB in size.",
		DisplayName: "Object Size 10MB",
	},
	{
		Name:        "object_size_100m",
		Type:        "custom.googleapis.com/fastly/object_size_100m",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of objects served that were between 10MB and 100MB in size.",
		DisplayName: "Object Size 100MB",
	},
	{
		Name:        "object_size_1g",
		Type:        "custom.googleapis.com/fastly/object_size_1g",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "1/s",
		Description: "Number of objects served that were between 100MB and 1GB in size.",
		DisplayName: "Object Size 11g",
	},
	{
		Name:        "billed_header_bytes",
		Type:        "custom.googleapis.com/fastly/billed_header_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Number of header bytes used as basis for billing.",
		DisplayName: "Billed Header Bytes",
	},
	{
		Name:        "billed_body_bytes",
		Type:        "custom.googleapis.com/fastly/billed_body_bytes",
		MetricKind:  metric.MetricDescriptor_GAUGE,
		ValueType:   metric.MetricDescriptor_INT64,
		Unit:        "By/s",
		Description: "Number of body bytes used as basis for billing.",
		DisplayName: "Billed Body Bytes",
	},
}
